version: '3.3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: vyshnavpc/nodejs_image:latest
    ports:
      - "4500:4500"
    restart: always
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    image: vyshnavpc/nginx_image:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
